server:
  port: 8080

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    gcp:
        project-id: ${GCP_PROJECT_ID:sonarqube-289802}

pubsub:
  topic-id: nasher.info
