server:
  port: 8081

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: gcp
  cloud:
    gcp:
        project-id: ${GCP_PROJECT_ID:sonarqube-289802}

pubsub:
  topic-id: ${PUB_SUB_TOPIC:nasher.info}
