apiVersion: apps/v1
kind: Deployment
metadata:
  name: contributionservice
  labels:
    app: contributionservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: contributionservice
  template:
    metadata:
      labels:
        app: contributionservice
    spec:
      containers:
        - name: contributionservice
          image: us-east1-docker.pkg.dev/sonarqube-289802/competency-insights/contribution-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
      imagePullSecrets:
        - name: regcred
---


apiVersion: v1
kind: Service
metadata:
  name: contributionservice
  labels:
    app: contributionservice
spec:
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  selector:
    app: contributionservice
  type: LoadBalancer
